[workspace]
resolver = "2"
members = [
    "crates/foxcrush",
    "crates/foxcrush/xtask",
]
default-members = ["crates/foxcrush"]

[workspace.package]
edition = "2021"
license = "GPL-3.0-or-later"
repository = "https://github.com/foxfire/foxplugs"

[workspace.metadata]
name = "foxplugs"

[profile.release]
lto = "thin"
strip = "symbols"

[profile.profiling]
inherits = "release"
debug = true
strip = "none"
